"""Add click_count and created_at

Revision ID: 76c65b86a331
Revises: 6a2d694feb8c
Create Date: 2026-07-06 11:53:36.385975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c65b86a331'
down_revision = '6a2d694feb8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('click_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('original_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('short_code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('urls_short_code_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_urls_short_code'), ['short_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urls_short_code'))
        batch_op.create_unique_constraint(batch_op.f('urls_short_code_key'), ['short_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('short_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('original_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('click_count')

    # ### end Alembic commands ###
